vim9script

g:mapleader = ','

# TODO
# - Select-mode?

import "~/.config/vim/pack.vim"
# import "~/.config/vim/remap.vim"
import "~/.config/vim/pops.vim"
import "~/.config/vim/web.vim"
import "~/.config/vim/ts.vim"

import "~/.config/vim/lsp.vim"
import "~/.config/vim/color.vim"
import "~/.config/vim/fzf.vim"

# Interface stuff
set encoding=UTF-8
set nocompatible
set laststatus=2
set tabline=2
set noshowmode
set number
set relativenumber
set splitbelow
set ttimeoutlen=0
set timeoutlen=500
set wildmenu
set bg=dark
set viminfo='0,<50,s10,h
syntax on

# Buffer stuff
set autoread
set hlsearch
set incsearch

# Editing Stuff
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set linebreak
set autoindent
set smartindent
set nowrap
set backspace=indent,eol,start
filetype plugin indent on

# Other files
set suffixesadd=.js
set updatetime=1000
set undofile
set undodir=~/.vim/undos
set tags=~/.vim/tags
set directory=~/tmp
set backupdir=~/tmp
set undodir=~/tmp

# Nops
nmap <Up> <Nop>
nmap <Down> <Nop>
nmap <Left> <Nop>
nmap <Right> <Nop>

## Close then type
# inoremap <> <><Left> # while tinkering with html
inoremap () ()<Left>
inoremap {} {}<Left>
inoremap [] []<Left>
inoremap "" ""<Left>
inoremap '' ''<Left>
inoremap `` ``<Left>
inoremap {<CR> {}<Left><CR><Esc>ko<C-f>
inoremap {<Space> {<Space><Space>}<Left><Left>
inoremap (<CR> ()<Left><CR><Esc>ko<C-f>
inoremap (<Space> (<Space><Space>)<Left><Left>
inoremap [<CR> []<Left><CR><Esc>ko<C-f>
inoremap [<Space> [<Space><Space>]<Left><Left>

inoremap <C-a> <Esc>%%a

# Windows/Splits

## Window navigation
nnoremap <C-h> <C-w><Left>
nnoremap <C-j> <C-w><Down>
nnoremap <C-k> <C-w><Up>
nnoremap <C-l> <C-w><Right>
tnoremap <C-h> <C-w><Left>
tnoremap <C-j> <C-w><Down>
tnoremap <C-k> <C-w><Up>
tnoremap <C-l> <C-w><Right>

## Window Manipulation
nnoremap <leader>/ <C-w>s
nnoremap <leader>\ <C-w>v
nnoremap <leader>- :res<CR>
nnoremap <leader>= <C-w>=

nnoremap <C-Right> <C-w>L
nnoremap <C-Left> <C-w>H
nnoremap <C-Down> <C-w>J
nnoremap <C-Up> <C-w>K
nnoremap <S-Left> <C-w><
nnoremap <S-Right> <C-w>>
nnoremap <S-Up> <C-w>+
nnoremap <S-Down> <C-w>-

# Buffers

## Switching buffers
nnoremap <leader>q :bp<bar>sp<bar>bn<bar>bd<CR>
# nnoremap <Tab> :bnext<CR>
# nnoremap <S-Tab> :bprev<CR>
nnoremap <leader>bd :b#<bar>:bd#<CR>

# call setbufvar(bufnr, 'buflisted', 0)  # Allows tab through?

nnoremap <leader><space> :noh<CR>

nnoremap <F8> :source %<CR>
