#!/bin/bash

# some aliases
alias ls='LC_COLLATE=C ls -F --group-directories-first --color=auto'
alias ll='ls -l'
alias la='ls -la'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias gs='git status'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias gj='git pull'
alias gf='git fetch'
alias gd='git diff'

alias cdu='cd ..'

alias tmux="tmux -2 -f $HOME/.config/tmux/tmux.conf"

alias tree="tree -I node_modules"

alias npmig="npm --prefix=$HOME/.local i -g"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

