# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

shopt -s histappend
shopt -s checkwinsize
shopt -s direxpand

[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

eval "$(dircolors -b)"

. $HOME/.config/bash/alias
. $HOME/.config/bash/env
. $HOME/.config/bash/complete
. $HOME/.config/bash/prompt

scent
